//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoPlurk.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChronoPlurk.Resources.i18n.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string autoRotateAlways {
            get {
                return ResourceManager.GetString("autoRotateAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose only.
        /// </summary>
        public static string autoRotateComposeOnly {
            get {
                return ResourceManager.GetString("autoRotateComposeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string autoRotateNever {
            get {
                return ResourceManager.GetString("autoRotateNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose friends.
        /// </summary>
        public static string chooseFriends {
            get {
                return ResourceManager.GetString("chooseFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This timeline is empty..
        /// </summary>
        public static string emptyTimeline {
            get {
                return ResourceManager.GetString("emptyTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re plurking with same content too many times, try change your content..
        /// </summary>
        public static string errAntiFloodSameContent {
            get {
                return ResourceManager.GetString("errAntiFloodSameContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re plurking too many in a short time. Please try again later..
        /// </summary>
        public static string errAntiFloodTooManyNew {
            get {
                return ResourceManager.GetString("errAntiFloodTooManyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is empty.
        /// </summary>
        public static string errContentIsEmpty {
            get {
                return ResourceManager.GetString("errContentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already found.
        /// </summary>
        public static string errEmailAlreadyFound {
            get {
                return ResourceManager.GetString("errEmailAlreadyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        public static string errEmailInvalid {
            get {
                return ResourceManager.GetString("errEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal service error. Could not plurk. Try again in a minute..
        /// </summary>
        public static string errInternalServiceError {
            get {
                return ResourceManager.GetString("errInternalServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string errInvalidData {
            get {
                return ResourceManager.GetString("errInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        public static string errInvalidFile {
            get {
                return ResourceManager.GetString("errInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Invalid nickname or password..
        /// </summary>
        public static string errInvalidLogin {
            get {
                return ResourceManager.GetString("errInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current passwords.
        /// </summary>
        public static string errInvalidPassword {
            get {
                return ResourceManager.GetString("errInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user_id.
        /// </summary>
        public static string errInvalidUserId {
            get {
                return ResourceManager.GetString("errInvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be friends.
        /// </summary>
        public static string errMustBeFriends {
            get {
                return ResourceManager.GetString("errMustBeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name too long, should be less than 15 characters long.
        /// </summary>
        public static string errNameTooLong {
            get {
                return ResourceManager.GetString("errNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name can only contain letters, numbers and _.
        /// </summary>
        public static string errNicknameCharError {
            get {
                return ResourceManager.GetString("errNicknameCharError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name must be at least 3 characters long.
        /// </summary>
        public static string errNicknameTooSmall {
            get {
                return ResourceManager.GetString("errNicknameTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permissions.
        /// </summary>
        public static string errNoPermissions {
            get {
                return ResourceManager.GetString("errNoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported image format or image too big.
        /// </summary>
        public static string errNotSupportedImage {
            get {
                return ResourceManager.GetString("errNotSupportedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        public static string errorOccured {
            get {
                return ResourceManager.GetString("errorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too small.
        /// </summary>
        public static string errPasswordTooSmall {
            get {
                return ResourceManager.GetString("errPasswordTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plurk not found.
        /// </summary>
        public static string errPlurkNotFound {
            get {
                return ResourceManager.GetString("errPlurkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plurk owner not found.
        /// </summary>
        public static string errPlurkOwnerNotFound {
            get {
                return ResourceManager.GetString("errPlurkOwnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires login to continue. Redirecting to login page..
        /// </summary>
        public static string errRequiresLogin {
            get {
                return ResourceManager.GetString("errRequiresLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many logins.
        /// </summary>
        public static string errTooManyLogins {
            get {
                return ResourceManager.GetString("errTooManyLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown problems on Plurk service..
        /// </summary>
        public static string errUnknown {
            get {
                return ResourceManager.GetString("errUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already befriended.
        /// </summary>
        public static string errUserAlreadyBefriended {
            get {
                return ResourceManager.GetString("errUserAlreadyBefriended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already found.
        /// </summary>
        public static string errUserAlreadyFound {
            get {
                return ResourceManager.GetString("errUserAlreadyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can&apos;t be befriended.
        /// </summary>
        public static string errUserCantBefriended {
            get {
                return ResourceManager.GetString("errUserCantBefriended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string errUserNotFound {
            get {
                return ResourceManager.GetString("errUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked.
        /// </summary>
        public static string filterLiked {
            get {
                return ResourceManager.GetString("filterLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my.
        /// </summary>
        public static string filterMy {
            get {
                return ResourceManager.GetString("filterMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        public static string filterPrivate {
            get {
                return ResourceManager.GetString("filterPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responded.
        /// </summary>
        public static string filterResponded {
            get {
                return ResourceManager.GetString("filterResponded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeline.
        /// </summary>
        public static string filterTimeline {
            get {
                return ResourceManager.GetString("filterTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your first time using friends list.\nFriends list will download automatically..
        /// </summary>
        public static string friendsListFirst {
            get {
                return ResourceManager.GetString("friendsListFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap items on left column to select.\n\nIn order to update friends list manually, you have to click download button at the menu bar..
        /// </summary>
        public static string friendsListHelp {
            get {
                return ResourceManager.GetString("friendsListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        public static string like {
            get {
                return ResourceManager.GetString("like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname or email.
        /// </summary>
        public static string loginNicknameOrEmail {
            get {
                return ResourceManager.GetString("loginNicknameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string loginPassword {
            get {
                return ResourceManager.GetString("loginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string msgConnecting {
            get {
                return ResourceManager.GetString("msgConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Profile.
        /// </summary>
        public static string msgCreatingProfile {
            get {
                return ResourceManager.GetString("msgCreatingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Friends List.
        /// </summary>
        public static string msgDownloadingFriendsList {
            get {
                return ResourceManager.GetString("msgDownloadingFriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string msgLoading {
            get {
                return ResourceManager.GetString("msgLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Responses.
        /// </summary>
        public static string msgLoadingResponses {
            get {
                return ResourceManager.GetString("msgLoadingResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching.
        /// </summary>
        public static string msgSearching {
            get {
                return ResourceManager.GetString("msgSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string msgSending {
            get {
                return ResourceManager.GetString("msgSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Timeline.
        /// </summary>
        public static string msgUpdatingTimeline {
            get {
                return ResourceManager.GetString("msgUpdatingTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Photo.
        /// </summary>
        public static string msgUploadingPhoto {
            get {
                return ResourceManager.GetString("msgUploadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute.
        /// </summary>
        public static string mute {
            get {
                return ResourceManager.GetString("mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only my friends.
        /// </summary>
        public static string onlyMyFriends {
            get {
                return ResourceManager.GetString("onlyMyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        public static string records {
            get {
                return ResourceManager.GetString("records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        public static string reply {
            get {
                return ResourceManager.GetString("reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed.\nCheck your internet connection..
        /// </summary>
        public static string requestFailedMessage {
            get {
                return ResourceManager.GetString("requestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  responses.
        /// </summary>
        public static string responsesCount {
            get {
                return ResourceManager.GetString("responsesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 response.
        /// </summary>
        public static string responseSingle {
            get {
                return ResourceManager.GetString("responseSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string settingsAbout {
            get {
                return ResourceManager.GetString("settingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string settingsAccounts {
            get {
                return ResourceManager.GetString("settingsAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto rotate.
        /// </summary>
        public static string settingsAutoRotate {
            get {
                return ResourceManager.GetString("settingsAutoRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string settingsGeneral {
            get {
                return ResourceManager.GetString("settingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open source credits.
        /// </summary>
        public static string settingsOss {
            get {
                return ResourceManager.GetString("settingsOss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string timeHoursAgo {
            get {
                return ResourceManager.GetString("timeHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins ago.
        /// </summary>
        public static string timeMinsAgo {
            get {
                return ResourceManager.GetString("timeMinsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moments ago.
        /// </summary>
        public static string timeMomentsAgo {
            get {
                return ResourceManager.GetString("timeMomentsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout.\n\nPlurk service might be busy now.\nPress OK to retry.\nPress cancel to stop..
        /// </summary>
        public static string timeoutMessage {
            get {
                return ResourceManager.GetString("timeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} secs ago.
        /// </summary>
        public static string timeSecsAgo {
            get {
                return ResourceManager.GetString("timeSecsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd.
        /// </summary>
        public static string timeShort {
            get {
                return ResourceManager.GetString("timeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to main page.
        /// </summary>
        public static string toMainPage {
            get {
                return ResourceManager.GetString("toMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters..
        /// </summary>
        public static string tooManyCharacters {
            get {
                return ResourceManager.GetString("tooManyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. Unknown error on this application. Leave a note to us..
        /// </summary>
        public static string unhandledErrorMessage {
            get {
                return ResourceManager.GetString("unhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike.
        /// </summary>
        public static string unlike {
            get {
                return ResourceManager.GetString("unlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unmute.
        /// </summary>
        public static string unmute {
            get {
                return ResourceManager.GetString("unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something before you plurk!.
        /// </summary>
        public static string warnEmpty {
            get {
                return ResourceManager.GetString("warnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHO CAN SEE THIS PLURK?.
        /// </summary>
        public static string whoCanSee {
            get {
                return ResourceManager.GetString("whoCanSee", resourceCulture);
            }
        }
    }
}
