//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoPlurk.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChronoPlurk.Resources.i18n.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose friends.
        /// </summary>
        public static string chooseFriends {
            get {
                return ResourceManager.GetString("chooseFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This timeline is empty..
        /// </summary>
        public static string emptyTimeline {
            get {
                return ResourceManager.GetString("emptyTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        public static string errorOccured {
            get {
                return ResourceManager.GetString("errorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked.
        /// </summary>
        public static string filterLiked {
            get {
                return ResourceManager.GetString("filterLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my.
        /// </summary>
        public static string filterMy {
            get {
                return ResourceManager.GetString("filterMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        public static string filterPrivate {
            get {
                return ResourceManager.GetString("filterPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responded.
        /// </summary>
        public static string filterResponded {
            get {
                return ResourceManager.GetString("filterResponded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeline.
        /// </summary>
        public static string filterTimeline {
            get {
                return ResourceManager.GetString("filterTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your first time using friends list.\nFriends list will download automatically..
        /// </summary>
        public static string friendsListFirst {
            get {
                return ResourceManager.GetString("friendsListFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap items on left column to select.\n\nIn order to update friends list manually, you have to click download button at the menu bar..
        /// </summary>
        public static string friendsListHelp {
            get {
                return ResourceManager.GetString("friendsListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        public static string like {
            get {
                return ResourceManager.GetString("like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname or email.
        /// </summary>
        public static string loginNicknameOrEmail {
            get {
                return ResourceManager.GetString("loginNicknameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string loginPassword {
            get {
                return ResourceManager.GetString("loginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string msgConnecting {
            get {
                return ResourceManager.GetString("msgConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Friends List.
        /// </summary>
        public static string msgDownloadingFriendsList {
            get {
                return ResourceManager.GetString("msgDownloadingFriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string msgLoading {
            get {
                return ResourceManager.GetString("msgLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Responses.
        /// </summary>
        public static string msgLoadingResponses {
            get {
                return ResourceManager.GetString("msgLoadingResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching.
        /// </summary>
        public static string msgSearching {
            get {
                return ResourceManager.GetString("msgSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string msgSending {
            get {
                return ResourceManager.GetString("msgSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Timeline.
        /// </summary>
        public static string msgUpdatingTimeline {
            get {
                return ResourceManager.GetString("msgUpdatingTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Photo.
        /// </summary>
        public static string msgUploadingPhoto {
            get {
                return ResourceManager.GetString("msgUploadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute.
        /// </summary>
        public static string mute {
            get {
                return ResourceManager.GetString("mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only my friends.
        /// </summary>
        public static string onlyMyFriends {
            get {
                return ResourceManager.GetString("onlyMyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        public static string records {
            get {
                return ResourceManager.GetString("records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        public static string reply {
            get {
                return ResourceManager.GetString("reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  responses.
        /// </summary>
        public static string responsesCount {
            get {
                return ResourceManager.GetString("responsesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 response.
        /// </summary>
        public static string responseSingle {
            get {
                return ResourceManager.GetString("responseSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string timeHoursAgo {
            get {
                return ResourceManager.GetString("timeHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins ago.
        /// </summary>
        public static string timeMinsAgo {
            get {
                return ResourceManager.GetString("timeMinsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moments ago.
        /// </summary>
        public static string timeMomentsAgo {
            get {
                return ResourceManager.GetString("timeMomentsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} secs ago.
        /// </summary>
        public static string timeSecsAgo {
            get {
                return ResourceManager.GetString("timeSecsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd.
        /// </summary>
        public static string timeShort {
            get {
                return ResourceManager.GetString("timeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to main page.
        /// </summary>
        public static string toMainPage {
            get {
                return ResourceManager.GetString("toMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters..
        /// </summary>
        public static string tooManyCharacters {
            get {
                return ResourceManager.GetString("tooManyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike.
        /// </summary>
        public static string unlike {
            get {
                return ResourceManager.GetString("unlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unmute.
        /// </summary>
        public static string unmute {
            get {
                return ResourceManager.GetString("unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something before you plurk!.
        /// </summary>
        public static string warnEmpty {
            get {
                return ResourceManager.GetString("warnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHO CAN SEE THIS PLURK?.
        /// </summary>
        public static string whoCanSee {
            get {
                return ResourceManager.GetString("whoCanSee", resourceCulture);
            }
        }
    }
}
